module.exports = {
  'balloons': require('react-native-ico-balloons/src/data/balloons'),
  'basic': require('react-native-ico-basic/src/data/basic'),
  'business': require('react-native-ico-business/src/data/business'),
  'coolicons': require('react-native-ico-coolicons/src/data/coolicons'),
  'essential': require('react-native-ico-essential/src/data/essential'),
  'file-folder': require('react-native-ico-file-folder/src/data/file-folder'),
  'flags': require('react-native-ico-flags/src/data/flags'),
  'font-awesome': require('react-native-ico-font-awesome/src/data/font-awesome'),
  'interaction': require('react-native-ico-interaction/src/data/interaction'),
  'lodgicons': require('react-native-ico-lodgicons/src/data/lodgicons'),
  'miscellaneous': require('react-native-ico-miscellaneous/src/data/miscellaneous'),
  'new-year': require('react-native-ico-new-year/src/data/new-year'),
  'payment-method': require('react-native-ico-payment-method/src/data/payment-method'),
  'shopping': require('react-native-ico-shopping/src/data/shopping'),
  'social-media': require('react-native-ico-social-media/src/data/social-media'),
  'ui-interface': require('react-native-ico-ui-interface/src/data/ui-interface'),
  'universalicons': require('react-native-ico-universalicons/src/data/universalicons'),
};
