module.exports = {
  'balloons': require('react-native-ico-balloons/src/data'),
  'basic': require('react-native-ico-basic/src/data'),
  'business': require('react-native-ico-business/src/data'),
  'coolicons': require('react-native-ico-coolicons/src/data'),
  'essential': require('react-native-ico-essential/src/data'),
  'file-folder': require('react-native-ico-file-folder/src/data'),
  'flags': require('react-native-ico-flags/src/data'),
  'font-awesome': require('react-native-ico-font-awesome/src/data'),
  'interaction': require('react-native-ico-interaction/src/data'),
  'lodgicons': require('react-native-ico-lodgicons/src/data'),
  'logistics-delivery': require('react-native-ico-logistics-delivery/src/data'),
  'material-design': require('react-native-ico-material-design/src/data'),
  'miscellaneous': require('react-native-ico-miscellaneous/src/data'),
  'new-year': require('react-native-ico-new-year/src/data'),
  'payment-method': require('react-native-ico-payment-method/src/data'),
  'shopping': require('react-native-ico-shopping/src/data'),
  'social-media': require('react-native-ico-social-media/src/data'),
  'stylish': require('react-native-ico-stylish/src/data'),
  'ui-interface': require('react-native-ico-ui-interface/src/data'),
  'universalicons': require('react-native-ico-universalicons/src/data'),
};
